# Generated by Django 6.0.6 on 2026-07-08 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0006_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assignee_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='assignor_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='company_name',
            field=models.CharField(choices=[('ARACO', 'ARACO Company'), ('JODAH', 'JODAH Company'), ('XYZ', 'XYZ Company')], default='ARACO', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='task_details',
            field=models.TextField(blank=True),
        ),
    ]
