# Generated by Django 6.0.6 on 2026-07-08 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TMS", "0007_task_assignee_notes_task_assignor_remarks_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="assignee_notes",
        ),
        migrations.RemoveField(
            model_name="task",
            name="assignor_remarks",
        ),
    ]
