# Generated by Django 6.0.6 on 2026-07-11 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TMS", "0012_taskreadstatus"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="activity_attachments/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="TMS.taskactivity",
                    ),
                ),
            ],
        ),
    ]
