# Generated by Django 6.0.6 on 2026-07-14 07:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TMS", "0013_activityattachment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="followers",
            field=models.ManyToManyField(
                blank=True, related_name="following_tasks", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
