# Generated by Django 6.0.7 on 2026-07-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TMS", "0016_usertaskstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="ai_summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="ai_summary_updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
