# Generated by Django 6.0.7 on 2026-07-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TMS", "0018_executivedigest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="company_name",
            field=models.CharField(
                choices=[
                    ("ARACO", "ARACO"),
                    ("JODAH", "JODAH"),
                    ("AL-KIFAH", "AL-KIFAH"),
                ],
                default=None,
                max_length=20,
            ),
        ),
    ]
