# Generated by Django 6.0.7 on 2026-07-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TMS", "0019_alter_task_company_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="company_name",
            field=models.CharField(
                choices=[
                    ("ARACO", "ARACO"),
                    ("JODAH", "JODAH"),
                    ("AL-KIFAH", "AL-KIFAH"),
                ],
                max_length=20,
            ),
        ),
    ]
