# Generated by Django 6.0.7 on 2026-07-29

import django.db.models.deletion
from django.db import migrations, models


def migrate_company_data(apps, schema_editor):
    Task = apps.get_model("TMS", "Task")
    Company = apps.get_model("TMS", "Company")

    # Create Company records from existing task values
    names = (
        Task.objects.exclude(company_name__isnull=True)
        .exclude(company_name="")
        .values_list("company_name", flat=True)
        .distinct()
    )

    company_map = {}
    for name in names:
        company, _ = Company.objects.get_or_create(name=name)
        company_map[name] = company

    # Populate the temporary FK
    for task in Task.objects.all():
        if task.company_name:
            task.company_fk = company_map[task.company_name]
            task.save(update_fields=["company_fk"])


class Migration(migrations.Migration):

    dependencies = [
        ("TMS", "0020_alter_task_company_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="task",
            name="company_fk",
            field=models.ForeignKey(
                to="TMS.company",
                on_delete=django.db.models.deletion.PROTECT,
                null=True,
            ),
        ),
        migrations.RunPython(
            migrate_company_data,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="task",
            name="company_name",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="company_fk",
            new_name="company_name",
        ),
        migrations.AlterField(
            model_name="task",
            name="company_name",
            field=models.ForeignKey(
                to="TMS.company",
                on_delete=django.db.models.deletion.PROTECT,
            ),
        ),
    ]
