# Generated by Django 6.0.7 on 2026-07-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TMS", "0020_alter_task_company_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="company_name",
            field=models.CharField(
                choices=[
                    ("ARACO", "ARACO"),
                    ("ASDAAM", "ASDAAM"),
                    ("BAFCO", "BAFCO"),
                    ("FREIGHTCARE", "FREIGHTCARE"),
                    ("IMPEX", "IMPEX"),
                    ("JODAH", "JODAH"),
                    ("LONESTAR", "LONESTAR"),
                    ("McMin", "McMin"),
                    ("PERSONAL", "PERSONAL"),
                    ("PFC", "PFC"),
                    ("SKYLAND", "SKYLAND"),
                    ("YESLA", "YESLA"),
                ],
                max_length=20,
            ),
        ),
    ]
