# Generated by Django 6.0.7 on 2026-07-29 13:08

import django.db.models.deletion
from django.db import migrations, models


def populate_companies(apps, schema_editor):
    Task = apps.get_model("TMS", "Task")
    Company = apps.get_model("TMS", "Company")

    names = (
        Task.objects.exclude(company_name__isnull=True)
        .exclude(company_name="")
        .values_list("company_name", flat=True)
        .distinct()
    )

    for name in names:
        Company.objects.get_or_create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ("TMS", "0020_alter_task_company_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.RunPython(
            populate_companies,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="task",
            name="company_name",
            field=models.ForeignKey(
                to="TMS.company",
                to_field="name",
                on_delete=django.db.models.deletion.PROTECT,
            ),
        ),
    ]
