# Generated by Django 6.0.7 on 2026-07-29 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TMS", "0020_alter_task_company_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="task",
            name="company_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="TMS.company",
                to_field="name",
            ),
        ),
    ]
